nodeLinker: node-modules

npmScopes:
    3dsteam:
        npmAlwaysAuth: true
        npmRegistryServer: "https://npm.pkg.github.com"
    awesome.me:
        npmAlwaysAuth: true
        npmRegistryServer: "https://npm.fontawesome.com/"
    fortawesome:
        npmAlwaysAuth: true
        npmRegistryServer: "https://npm.fontawesome.com/"
